# Generated by Django 5.0.6 on 2026-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('deco', 'Décoration'), ('formation', 'Formation (Academy)'), ('realisation', 'Réalisations (portfolio)'), ('accessoire', 'Location de matériel')], max_length=20)),
                ('image', models.ImageField(upload_to='landing/')),
                ('label', models.CharField(max_length=150)),
                ('caption', models.CharField(blank=True, help_text="Légende courte affichée sous l'image", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (croissant)")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Média page d'accueil",
                'verbose_name_plural': "Médias page d'accueil",
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
