# Generated by Django 5.0.6 on 2026-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_landingmedia_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingmedia',
            name='price_label',
            field=models.CharField(blank=True, help_text='Prix indicatif affiché sur la page publique, ex : « 5 000 FCFA / chaise / jour » (catégorie « Location de matériel »)', max_length=100),
        ),
    ]
