# Generated by Django 5.0.6 on 2026-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_landingmedia_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingmedia',
            name='budget_label',
            field=models.CharField(blank=True, help_text='Budget indicatif affiché sur la page publique, ex : « À partir de 1 200 000 FCFA » (catégorie « Réalisations »)', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingmedia',
            name='caption',
            field=models.CharField(blank=True, help_text="Légende courte / description affichée sous l'image", max_length=200),
        ),
        migrations.AlterField(
            model_name='landingmedia',
            name='tag',
            field=models.CharField(blank=True, help_text="Type d'événement / catégorie de réalisation (ex : Mariage, Gala, Corporate, Baptême…). Texte libre : l'administrateur peut créer de nouvelles catégories à la volée. Utilisé pour le filtre de la galerie (catégorie « Réalisations » uniquement).", max_length=50),
        ),
    ]
