# Generated by Django 5.0.6 on 2026-09-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_landingmedia_budget_label_alter_landingmedia_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingmedia',
            name='scope',
            field=models.CharField(blank=True, choices=[('prive', 'Événements privés'), ('public', 'Événements grand public')], help_text='Événements privés ou grand public — catégorie « Réalisations » uniquement.', max_length=10),
        ),
        migrations.AddField(
            model_name='landingmedia',
            name='tier',
            field=models.CharField(blank=True, choices=[('haut', 'Haut de gamme'), ('moyen', 'Moyenne gamme'), ('petit', 'Petite gamme')], help_text="Gamme de la réalisation : détermine l'ordre d'affichage (haut de gamme en premier) — catégorie « Réalisations » uniquement.", max_length=10),
        ),
        migrations.AlterField(
            model_name='landingmedia',
            name='budget_label',
            field=models.CharField(blank=True, help_text='Prix du pack affiché sur la page publique, ex : « 1 200 000 FCFA » (catégorie « Nos packs »)', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingmedia',
            name='category',
            field=models.CharField(choices=[('deco', 'Décoration'), ('formation', 'Formation (Academy)'), ('realisation', 'Réalisations (portfolio)'), ('accessoire', 'Location de matériel'), ('pack', 'Nos packs (offres tarifées)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='landingmedia',
            name='tag',
            field=models.CharField(blank=True, help_text="Type d'événement au sein du scope choisi (ex : Mariages Modernes, Anniversaires Adultes, Salons…). Texte libre : l'administrateur peut créer de nouveaux types à la volée. Utilisé pour le filtre de la galerie (catégorie « Réalisations » uniquement).", max_length=50),
        ),
    ]
