# Generated by Django 5.0.6 on 2026-09-14 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_stockmovement_expense'),
        ('providers', '0006_alter_provider_category'),
        ('public', '0005_landingmedia_scope_landingmedia_tier_and_more'),
        ('venues', '0002_venue_discount_label_venue_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('venue', 'Salle'), ('provider', 'Prestataire'), ('equipment', 'Matériel')], max_length=20)),
                ('default_quantity', models.PositiveIntegerField(default=1, help_text="Utilisé pour le matériel (nombre d'unités suggéré)")),
                ('is_optional', models.BooleanField(default=False, help_text='Élément additionnel proposé en option, non inclus par défaut dans le pack')),
                ('order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='equipment.equipment')),
                ('pack', models.ForeignKey(limit_choices_to={'category': 'pack'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='public.landingmedia')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='providers.provider')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='venues.venue')),
            ],
            options={
                'ordering': ['pack', 'order', 'id'],
            },
        ),
    ]
