# Generated by Django 5.0.6 on 2026-09-19 12:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0018_professionalprofile_id_card_photo'),
        ('payments', '0003_alter_payment_provider'),
        ('providers', '0010_alter_provider_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente (inscrit, pas encore de transaction validée)'), ('converted', 'Converti (filleul actif)'), ('reversed', 'Annulé (remboursement/annulation de la transaction)')], default='pending', max_length=20)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Suspecté de fraude — visible dans le tableau de bord admin.')),
                ('flag_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('first_conversion_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_record', to='payments.payment')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_records', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('terms_text', models.TextField(blank=True, help_text="Conditions d'utilisation affichées au filleul/parrain.")),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Campagne appliquée par défaut aux conversions qui ne correspondent à aucune campagne ciblée.')),
                ('category', models.CharField(blank=True, choices=[('wedding_planner', 'Wedding Planner / Event Planner'), ('mc', 'Maître de Cérémonie (MC) - Bilingue'), ('protocol', "Protocole / Hôtesses d'accueil"), ('pco_agency', 'Agence PCO - Organisateur de Conférences / Salons'), ('team_building_coach', 'Coach / Formateur Team Building'), ('venue_rental', 'Location de salle / Villa / Domaine / Hôtel / Jardin / Piscine'), ('tent_rental', 'Location de chapiteaux / Tentes / Bâches / Structures'), ('furniture_rental', 'Location de mobilier : Chaises (Tiffany, Chiavari, Plastique), Tables, Nappes, Housses'), ('tableware_rental', 'Location de vaisselle / Verrerie / Couverts / Chauffe-plats'), ('generator_electrician', 'Location de Groupe Électrogène + Électricien / Technicien'), ('security', 'Service de Sécurité / Agent / Videur / Sécurité rapprochée'), ('cleaning_service', 'Service de Nettoyage / Remise en état'), ('decoration', 'Décorateur / Designer Événementiel / Scénographe'), ('florist', 'Fleuriste événementiel'), ('centerpiece_rental', 'Location Décor : Centre de table, Arche, Backdrop, Moquette, Lustres'), ('balloon_artist', 'Artiste Ballon / Décorateur Ballons organiques'), ('lighting', "Éclairagiste d'ambiance / Éclairage architectural"), ('caterer', 'Traiteur / Chef à domicile / Buffet / Rôtisseur'), ('pastry', 'Pâtissier / Cake Designer / Glacier / Fontaine Chocolat'), ('bartender', 'Barman / Mixologue / Service Bar Mobile'), ('waitstaff', 'Serveur / Serveuse Professionnel(le)'), ('photography', 'Photographe (Mariage, Corporate, Anniversaire)'), ('video', 'Vidéaste / Cameraman / Pilote Drone / Retransmission Live'), ('photobooth', 'Photobooth / Miroir Photo / 360° Booth / Audioguestbook'), ('dj', 'DJ / Disc-Jockey'), ('sound', 'Technicien Sonorisation / Location Sono Complète / Traducteur Simultané'), ('stage_lighting', 'Technicien Lumière / Jeux de lumière / Fumigène / Écran LED'), ('live_band', 'Groupe Live / Orchestre / Artiste / Chanteur / Saxophoniste'), ('animation', 'Animateur / Danseurs / Troupe de danse'), ('entertainer', 'Humoriste / Magicien / Cracheur de feu / Échassier'), ('mascot', 'Mascottes / Personnages pour enfants / Clown'), ('games_rental', 'Location de Jeux : Château Gonflable, Trampoline, Jeux en bois, Baby-foot'), ('makeup_artist', 'Maquilleuse (MUA) / Coiffeuse / Prothésiste Ongulaire'), ('stylist', 'Styliste / Créateur de Robes / Tailleur Costume sur-mesure'), ('costume_rental', 'Location de Tenues Traditionnelles / Costumes / Voiles'), ('jeweler', "Bijoutier / Créateur d'Alliances / Loueur de Bijoux"), ('luxury_car_rental', 'Location de Voitures de Luxe / Limousine / Voiture Mariés'), ('guest_transport', 'Location de Bus / Navette / Transport Invités / Voiturier'), ('hotel_booking', 'Réservation Hôtel / Hébergement Invités / Accueil Aéroport'), ('printing', 'Imprimeur : Faire-part, Invitations, Menus, Badges, Roll-up, Kakemono, Banderoles'), ('childcare_service', "Service Nounou / Gardiennage d'Enfants pour événement"), ('trophy_rental', 'Loueur de Trophées / Awards pour Gala'), ('ice_cream_fountain', 'Glacier / Fontaine à chocolat'), ('guestbook', "Livre d'or / Audioguest"), ('hairdresser', 'Coiffeuse'), ('manicure', 'Manucure / Onglerie'), ('website_creator', "Créateur de site web pour l'événement"), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre'), ('landscape_architect', "Architecte d'extérieur / Paysagiste"), ('interior_decorator', "Décorateur d'intérieur"), ('home_stager', 'Home Stager'), ('design_3d_visualizer', 'Dessinateur 3D / Visualiseur'), ('technical_design_office', "Bureau d'études (plans techniques)"), ('carpentry_joinery', 'Menuiserie / Ébénisterie (cuisine, dressing sur-mesure)'), ('painting_wall_coverings', 'Peinture & Revêtements muraux'), ('tiling_flooring', 'Carrelage & Revêtements de sol'), ('ceiling_staff_work', 'Plafonds & Staff'), ('home_electrician_lighting', 'Électricité & Éclairage'), ('plumbing_sanitary', 'Plomberie & Sanitaire'), ('garden_landscaping', 'Aménagement de jardin & espaces verts'), ('terrace_pergola_poolhouse', 'Terrasse, pergola, pool house'), ('pool_builder', 'Pisciniste'), ('facade_fencing_gates', 'Façade, clôture & portails'), ('outdoor_lighting', 'Éclairage extérieur'), ('custom_standard_furniture', 'Mobilier sur-mesure & standard'), ('lighting_fixtures', 'Luminaires'), ('fabrics_curtains_linens', 'Tissus, rideaux, linge de maison'), ('decor_art_objects', 'Objets déco & art'), ('material_suppliers', 'Fournisseurs de matériaux (bois, pierre, carrelage, peinture)'), ('general_contractor', "Entreprise générale / Maître d'œuvre"), ('moving_installation', 'Déménagement & Installation'), ('post_construction_cleaning', 'Nettoyage fin de chantier'), ('interior_photographer', "Photographe d'intérieur")], help_text='Vide = toutes catégories.', max_length=30)),
                ('marketplace_type', models.CharField(blank=True, help_text='Vide = tous les marketplaces.', max_length=20)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_validity_days', models.PositiveIntegerField(default=30)),
                ('max_uses_per_coupon', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_profiles', models.ManyToManyField(blank=True, related_name='referral_campaigns', to='marketplace.professionalprofile')),
                ('providers', models.ManyToManyField(blank=True, related_name='referral_campaigns', to='providers.provider')),
                ('services', models.ManyToManyField(blank=True, related_name='referral_campaigns', to='marketplace.professionalservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaignTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_referrals', models.PositiveIntegerField(help_text='Nombre de filleuls actifs nécessaires pour débloquer ce palier.')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('label', models.CharField(blank=True, help_text='Ex : « Avantage spécial » — affiché au lieu du pourcentage si renseigné.', max_length=150)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='referrals.referralcampaign')),
            ],
            options={
                'ordering': ['threshold_referrals'],
            },
        ),
        migrations.CreateModel(
            name='ReferralConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_qualifying', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('marketplace_type', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_conversion', to='payments.payment')),
                ('professional_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.professionalprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='providers.provider')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='available', max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='referrals.referralcampaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_coupons', to=settings.AUTH_USER_MODEL)),
                ('redeemed_payment', models.ForeignKey(blank=True, help_text='Dernier paiement ayant utilisé ce coupon (historique complet non nécessaire : la plupart des coupons sont à usage unique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to='payments.payment')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='referrals.referralcampaigntier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_r_status_50a3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer'], name='referrals_r_referre_18a7a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('referrer', models.F('referred_user')), _negated=True), name='referral_no_self_referral'),
        ),
        migrations.AddConstraint(
            model_name='referralcampaigntier',
            constraint=models.UniqueConstraint(fields=('campaign', 'threshold_referrals'), name='unique_tier_threshold_per_campaign'),
        ),
        migrations.AddIndex(
            model_name='rewardcoupon',
            index=models.Index(fields=['status'], name='referrals_r_status_c90828_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardcoupon',
            index=models.Index(fields=['owner'], name='referrals_r_owner_i_1f5ff8_idx'),
        ),
    ]
