# Generated by Django 5.0.6 on 2026-09-14 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Partenaire propriétaire de cette annonce (vide si publiée directement par l'administration).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MarketplaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_type', models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['marketplace_type'],
                'unique_together': {('user', 'marketplace_type')},
            },
        ),
    ]
