# Generated by Django 5.0.6 on 2026-09-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacelisting_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='requires_subscription',
            field=models.BooleanField(default=True, help_text='Coché : visible uniquement par les comptes abonnés à ce marketplace précis. Décoché : accès libre, visible par tout client connecté (« mode client simple »).'),
        ),
    ]
