# Generated by Django 5.0.6 on 2026-09-14 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplacelisting_requires_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_type', models.CharField(choices=[('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('dj', 'DJ'), ('caterer', 'Traiteur'), ('decoration', 'Décoration'), ('security', 'Sécurité'), ('photography', 'Photographie'), ('video', 'Vidéo'), ('pastry', 'Pâtisserie'), ('animation', 'Animation (MC, artistes, danseurs...)'), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('printing', 'Impression'), ('wedding_planner', 'Wedding planner'), ('florist', 'Fleuriste'), ('makeup_artist', 'Maquilleur(se)'), ('hairdresser', 'Coiffeur(se)'), ('sound', 'Sonorisation'), ('lighting', 'Éclairage'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre')], max_length=30)),
                ('business_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('team_presentation', models.TextField(blank=True, help_text="Présentation de l'équipe")),
                ('specialties', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, help_text='Quartier', max_length=100)),
                ('service_area', models.CharField(blank=True, help_text="Zone d'intervention (villes couvertes)", max_length=300)),
                ('conditions', models.TextField(blank=True, help_text='Conditions générales de prestation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marketplace/profiles/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='marketplace/profiles/covers/')),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Badge « Prestataire vérifié », accordé par l'administration.")),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('completed_projects_count', models.PositiveIntegerField(default=0, help_text='Nombre de prestations réalisées (mis à jour manuellement en attendant le suivi automatique des réservations).')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour masquer le profil sans le supprimer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/portfolio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='marketplace.professionalprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Prix fixe'), ('quote', 'Sur devis')], default='quote', max_length=10)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Prix à partir de (laisser vide si entièrement sur devis)', max_digits=12, null=True)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('duration_label', models.CharField(blank=True, help_text='Ex : 4 heures, 1 journée, week-end complet', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Nombre de personnes incluses', null=True)),
                ('conditions', models.CharField(blank=True, help_text='Conditions particulières à ce service', max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='marketplace/services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.professionalprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
