# Generated by Django 5.0.6 on 2026-09-14 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_professionalprofile_professionalportfolioitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Numéro auquel joindre le client pour la mise en relation', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Mise en relation effectuée'), ('confirmed', 'Confirmée'), ('declined', 'Refusée')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes de suivi — jamais visibles par le client ou le prestataire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_booking_requests', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='marketplace.professionalprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='marketplace.professionalservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
