# Generated by Django 5.0.6 on 2026-09-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_professionalbookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('level', models.PositiveIntegerField(default=0, help_text='Plus élevé = plus de privilèges ; sert à comparer les paliers entre eux.')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_default', models.BooleanField(default=False, help_text='Palier attribué par défaut à un nouvel abonnement.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'level'],
            },
        ),
        migrations.AddField(
            model_name='marketplacesubscription',
            name='tier',
            field=models.ForeignKey(blank=True, help_text="Palier souscrit — détermine l'accès aux fonctionnalités qui exigent un palier minimum.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='marketplace.subscriptiontier'),
        ),
        migrations.CreateModel(
            name='MarketplaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_type', models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs')], max_length=20)),
                ('key', models.SlugField(help_text='Identifiant technique stable, utilisé par le frontend (ex : book, contact, reviews).', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('visibility', models.CharField(choices=[('everyone', 'Tout le monde'), ('authenticated', 'Utilisateurs connectés'), ('non_subscriber', 'Utilisateurs non abonnés'), ('subscriber', 'Utilisateurs abonnés'), ('admin', 'Administrateurs uniquement')], default='subscriber', max_length=20)),
                ('state', models.CharField(choices=[('shown', 'Affiché'), ('hidden', 'Masqué'), ('locked', 'Verrouillé'), ('upsell', "Affiché avec message d'abonnement")], default='shown', max_length=20)),
                ('upsell_message', models.CharField(blank=True, help_text="Message affiché aux non-abonnés quand l'état est « Affiché avec message d'abonnement » ou « Verrouillé ».", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_tier', models.ForeignKey(blank=True, help_text='Palier minimum requis pour un utilisateur abonné (laisser vide = aucune exigence de palier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='marketplace.subscriptiontier')),
            ],
            options={
                'ordering': ['marketplace_type', 'order', 'id'],
                'unique_together': {('marketplace_type', 'key')},
            },
        ),
    ]
