# Generated by Django 5.0.6 on 2026-09-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_subscriptiontier_marketplacesubscription_tier_and_more'),
        ('payments', '0002_alter_payment_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='budget_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='event_type',
            field=models.CharField(blank=True, help_text="Ex : Mariage, Anniversaire, Séminaire d'entreprise", max_length=120),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de participants', null=True),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='location',
            field=models.CharField(blank=True, help_text="Lieu précis de l'événement", max_length=255),
        ),
        migrations.AddField(
            model_name='professionalbookingrequest',
            name='options_wanted',
            field=models.TextField(blank=True, help_text='Options souhaitées par le client'),
        ),
        migrations.AlterField(
            model_name='professionalbookingrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Description du besoin par le client'),
        ),
        migrations.AlterField(
            model_name='professionalbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de réponse'), ('quoted', 'Devis envoyé'), ('modification_requested', 'Modification demandée'), ('accepted', 'Devis accepté — paiement attendu'), ('confirmed', 'Confirmée (payée)'), ('completed', 'Prestation réalisée'), ('declined', 'Refusée'), ('cancelled', 'Annulée'), ('contacted', 'Mise en relation effectuée (suivi manuel)')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding_planner', 'Wedding planner / Event planner'), ('mc', 'Maître de cérémonie (MC)'), ('protocol', 'Protocole'), ('venue_rental', 'Location de salle / domaine / villa / hôtel'), ('tent_rental', 'Location de chapiteaux, tentes, bâches'), ('furniture_rental', 'Location de chaises, tables, nappes, housses'), ('tableware_rental', 'Location de vaisselle, verrerie, couverts'), ('generator_electrician', 'Groupe électrogène + électricien'), ('security', 'Sécurité / Agents de sécurité / Videur'), ('cleaning_service', 'Service de nettoyage'), ('decoration', 'Décorateur / Designer événementiel'), ('florist', 'Fleuriste'), ('centerpiece_rental', 'Location de centre de table, arche, backdrop'), ('balloon_artist', 'Ballons / Artiste en ballons'), ('lighting', "Éclairage d'ambiance / Scénographie"), ('caterer', 'Traiteur / Service traiteur'), ('pastry', 'Pâtissier / Cake designer'), ('ice_cream_fountain', 'Glacier / Fontaine à chocolat'), ('bartender', 'Barman / Service bar / Bar à cocktail'), ('waitstaff', 'Serveurs / Serveuses'), ('photography', 'Photographe'), ('video', 'Vidéaste / Cameraman / Drone'), ('photobooth', 'Photobooth / Miroir photo / 360° Booth'), ('guestbook', "Livre d'or / Audioguest"), ('dj', 'DJ / Disc-jockey'), ('live_band', 'Groupe live / Orchestre / Artistes / Chanteurs'), ('sound', 'Sonorisation / Technicien son'), ('stage_lighting', 'Éclairagiste / Jeux de lumière / Fumigène'), ('animation', 'Animateurs / Danseurs / Danseuses'), ('entertainer', 'Humoriste / Magicien / Cracheur de feu'), ('mascot', 'Mascottes / Personnages pour enfants'), ('games_rental', 'Location de jeux (château gonflable, etc.)'), ('stylist', 'Styliste / Créateur de robes / Costumier'), ('makeup_artist', 'Maquilleuse (MUA)'), ('hairdresser', 'Coiffeuse'), ('manicure', 'Manucure / Onglerie'), ('costume_rental', 'Location de costumes / tenues traditionnelles'), ('luxury_car_rental', 'Location de voitures de luxe / Limousine'), ('guest_transport', 'Transport invités (bus, navette)'), ('hotel_booking', 'Réservation hôtel pour invités'), ('printing', 'Imprimerie (faire-part, invitations, menus)'), ('website_creator', "Créateur de site web pour l'événement"), ('jeweler', "Loueur d'alliances / Bijoutier"), ('childcare_service', "Service de gardiennage d'enfants (nounou)"), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre')], max_length=30),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('conditions', models.TextField(blank=True, help_text='Conditions de prestation')),
                ('cancellation_policy', models.TextField(blank=True, help_text="Conditions d'annulation")),
                ('valid_until', models.DateField(blank=True, help_text="Date limite d'acceptation du devis", null=True)),
                ('provider_note', models.TextField(blank=True, help_text='Message du prestataire accompagnant le devis (réponse à une question, précision...)')),
                ('client_message', models.TextField(blank=True, help_text='Question ou demande de modification formulée par le client sur CE devis')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('modification_requested', 'Modification demandée'), ('expired', 'Expiré'), ('superseded', 'Remplacé par une nouvelle version')], default='sent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='marketplace.professionalbookingrequest')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.quote')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
