# Generated by Django 5.0.6 on 2026-09-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_professionalbookingrequest_budget_estimate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAvailabilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_notice_days', models.PositiveIntegerField(default=2, help_text='Délai minimum, en jours, avant une date réservable.')),
                ('max_bookings_per_day', models.PositiveIntegerField(default=1, help_text='Nombre maximum de prestations confirmées le même jour.')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings', to='marketplace.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='marketplace.professionalprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
