# Generated by Django 5.0.6 on 2026-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_professionalfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Badge « ★ Recommandé », accordé par l'administration."),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='is_top',
            field=models.BooleanField(default=False, help_text="Badge « 🏆 Top prestataire », accordé par l'administration."),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de consultations de la fiche (statistiques admin).'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Badge « ✓ Vérifié », accordé par l'administration."),
        ),
    ]
