# Generated by Django 5.0.6 on 2026-09-14 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_professionalprofile_is_recommended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_type', models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs')], max_length=20, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Pourcentage prélevé par InnovEvent sur chaque paiement de devis dans ce marketplace.', max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='provider_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
