# Generated by Django 5.0.6 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_commissionsettings_quote_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Position de la ville principale (recherche « près de moi »)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='max_distance_km',
            field=models.PositiveIntegerField(blank=True, help_text="Distance maximale d'intervention depuis la ville principale (km)", null=True),
        ),
    ]
