# Generated by Django 5.0.6 on 2026-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_professionalprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='country',
            field=models.CharField(default='CM', help_text='Code pays ISO 3166-1 alpha-2 (ex : CM). Préparé pour une expansion multi-pays future.', max_length=2),
        ),
    ]
