# Generated by Django 5.0.6 on 2026-09-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_stockmovement_expense'),
        ('marketplace', '0013_professionalprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_equipment', to='marketplace.professionalbookingrequest')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='equipment.equipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
