# Generated by Django 5.0.6 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_requestedequipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsettings',
            name='marketplace_type',
            field=models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs'), ('venues', 'Salles de réception')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='marketplacefeature',
            name='marketplace_type',
            field=models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs'), ('venues', 'Salles de réception')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='marketplace_type',
            field=models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs'), ('venues', 'Salles de réception')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacesubscription',
            name='marketplace_type',
            field=models.CharField(choices=[('sale', 'Marketplace vente'), ('interior_design', 'Décoration & design intérieur'), ('actors', 'Marketplace des acteurs'), ('venues', 'Salles de réception')], max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('wedding_planner', 'Wedding Planner / Event Planner'), ('mc', 'Maître de Cérémonie (MC) - Bilingue'), ('protocol', "Protocole / Hôtesses d'accueil"), ('pco_agency', 'Agence PCO - Organisateur de Conférences / Salons'), ('team_building_coach', 'Coach / Formateur Team Building'), ('venue_rental', 'Location de salle / Villa / Domaine / Hôtel / Jardin / Piscine'), ('tent_rental', 'Location de chapiteaux / Tentes / Bâches / Structures'), ('furniture_rental', 'Location de mobilier : Chaises (Tiffany, Chiavari, Plastique), Tables, Nappes, Housses'), ('tableware_rental', 'Location de vaisselle / Verrerie / Couverts / Chauffe-plats'), ('generator_electrician', 'Location de Groupe Électrogène + Électricien / Technicien'), ('security', 'Service de Sécurité / Agent / Videur / Sécurité rapprochée'), ('cleaning_service', 'Service de Nettoyage / Remise en état'), ('decoration', 'Décorateur / Designer Événementiel / Scénographe'), ('florist', 'Fleuriste événementiel'), ('centerpiece_rental', 'Location Décor : Centre de table, Arche, Backdrop, Moquette, Lustres'), ('balloon_artist', 'Artiste Ballon / Décorateur Ballons organiques'), ('lighting', "Éclairagiste d'ambiance / Éclairage architectural"), ('caterer', 'Traiteur / Chef à domicile / Buffet / Rôtisseur'), ('pastry', 'Pâtissier / Cake Designer / Glacier / Fontaine Chocolat'), ('bartender', 'Barman / Mixologue / Service Bar Mobile'), ('waitstaff', 'Serveur / Serveuse Professionnel(le)'), ('photography', 'Photographe (Mariage, Corporate, Anniversaire)'), ('video', 'Vidéaste / Cameraman / Pilote Drone / Retransmission Live'), ('photobooth', 'Photobooth / Miroir Photo / 360° Booth / Audioguestbook'), ('dj', 'DJ / Disc-Jockey'), ('sound', 'Technicien Sonorisation / Location Sono Complète / Traducteur Simultané'), ('stage_lighting', 'Technicien Lumière / Jeux de lumière / Fumigène / Écran LED'), ('live_band', 'Groupe Live / Orchestre / Artiste / Chanteur / Saxophoniste'), ('animation', 'Animateur / Danseurs / Troupe de danse'), ('entertainer', 'Humoriste / Magicien / Cracheur de feu / Échassier'), ('mascot', 'Mascottes / Personnages pour enfants / Clown'), ('games_rental', 'Location de Jeux : Château Gonflable, Trampoline, Jeux en bois, Baby-foot'), ('makeup_artist', 'Maquilleuse (MUA) / Coiffeuse / Prothésiste Ongulaire'), ('stylist', 'Styliste / Créateur de Robes / Tailleur Costume sur-mesure'), ('costume_rental', 'Location de Tenues Traditionnelles / Costumes / Voiles'), ('jeweler', "Bijoutier / Créateur d'Alliances / Loueur de Bijoux"), ('luxury_car_rental', 'Location de Voitures de Luxe / Limousine / Voiture Mariés'), ('guest_transport', 'Location de Bus / Navette / Transport Invités / Voiturier'), ('hotel_booking', 'Réservation Hôtel / Hébergement Invités / Accueil Aéroport'), ('printing', 'Imprimeur : Faire-part, Invitations, Menus, Badges, Roll-up, Kakemono, Banderoles'), ('childcare_service', "Service Nounou / Gardiennage d'Enfants pour événement"), ('trophy_rental', 'Loueur de Trophées / Awards pour Gala'), ('ice_cream_fountain', 'Glacier / Fontaine à chocolat'), ('guestbook', "Livre d'or / Audioguest"), ('hairdresser', 'Coiffeuse'), ('manicure', 'Manucure / Onglerie'), ('website_creator', "Créateur de site web pour l'événement"), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre')], max_length=30),
        ),
    ]
