# Generated by Django 5.0.6 on 2026-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_commissionsettings_marketplace_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('months', models.PositiveIntegerField(default=1, help_text='Nombre de mois couverts par cette formule.')),
                ('duration_days', models.PositiveIntegerField(help_text="Durée exacte en jours ajoutée à l'abonnement (permet un mois = 30 jours, etc.).")),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix total de la formule, en XAF.', max_digits=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Purement informatif — affiché comme badge de réduction.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'months'],
            },
        ),
    ]
