# Generated by Django 5.0.6 on 2026-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_professionalportfolioitem_before_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text="Photo de la CNI — vérification d'identité, à fournir une fois lors de la création du profil.", null=True, upload_to='marketplace/profiles/id_cards/'),
        ),
    ]
