# Generated by Django 5.0.6 on 2026-09-19 14:00

import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_professionalprofile_id_card_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/profiles/covers/', validators=[apps.documents.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text="Photo de la CNI — vérification d'identité, à fournir une fois lors de la création du profil.", null=True, upload_to='marketplace/profiles/id_cards/', validators=[apps.documents.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/profiles/', validators=[apps.documents.validators.validate_image_file]),
        ),
    ]
