# Generated by Django 5.0.6 on 2026-09-21 06:59
# Réordonné manuellement : le champ est ajouté et les données existantes
# migrées AVANT la suppression de l'ancien booléen, pour ne jamais perdre le
# statut « vérifié » des profils déjà accordés par l'administration.

from django.db import migrations, models


def migrate_is_verified_forward(apps, schema_editor):
    ProfessionalProfile = apps.get_model("marketplace", "ProfessionalProfile")
    ProfessionalProfile.objects.filter(is_verified=True).update(verification_status="profile_verified")


def migrate_is_verified_backward(apps, schema_editor):
    ProfessionalProfile = apps.get_model("marketplace", "ProfessionalProfile")
    ProfessionalProfile.objects.exclude(verification_status="not_verified").update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_alter_professionalprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Non vérifié'), ('profile_verified', 'Profil vérifié'), ('identity_verified', 'Identité vérifiée'), ('company_verified', 'Entreprise vérifiée'), ('portfolio_verified', 'Portfolio vérifié'), ('professional_partner', 'Partenaire professionnel')], default='not_verified', help_text="Statut de vérification, accordé par l'administration (section 6 du CDC).", max_length=25),
        ),
        migrations.RunPython(migrate_is_verified_forward, migrate_is_verified_backward),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='is_verified',
        ),
    ]
