# Generated by Django 5.0.6 on 2026-09-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Créée'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('to_prepare', 'À préparer'), ('ready', 'Prête à récupérer'), ('carrier_assigned', 'Transporteur affecté'), ('collected', 'Collectée'), ('in_transit', 'En transit'), ('arrived', 'Arrivée à destination'), ('delivering', 'En cours de livraison'), ('delivered', 'Livrée'), ('failed', 'Échec de livraison'), ('postponed', 'Reportée'), ('cancelled', 'Annulée'), ('returning', 'Retour en cours'), ('returned', 'Retournée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('created', 'Créée'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('to_prepare', 'À préparer'), ('ready', 'Prête à récupérer'), ('carrier_assigned', 'Transporteur affecté'), ('collected', 'Collectée'), ('in_transit', 'En transit'), ('arrived', 'Arrivée à destination'), ('delivering', 'En cours de livraison'), ('delivered', 'Livrée'), ('failed', 'Échec de livraison'), ('postponed', 'Reportée'), ('cancelled', 'Annulée'), ('returning', 'Retour en cours'), ('returned', 'Retournée')], max_length=20),
        ),
    ]
