# Generated by Django 5.0.6 on 2026-09-17 05:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_deliverystatushistory_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Carburant'), ('toll', 'Péage'), ('maintenance', 'Entretien'), ('parking', 'Stationnement'), ('other', 'Autre')], default='fuel', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='deliveries.carrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='deliveries.delivery')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='deliveries.vehicle')),
            ],
            options={
                'verbose_name': 'Dépense transport',
                'verbose_name_plural': 'Dépenses transport',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('refused', 'Refusé par le destinataire'), ('damaged', 'Colis endommagé'), ('wrong_address', 'Adresse erronée'), ('client_absent', 'Destinataire absent'), ('other', 'Autre')], max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('refund_status', models.CharField(choices=[('none', 'Aucun remboursement'), ('pending', 'Remboursement en attente'), ('done', 'Remboursé')], default='none', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='deliveries.delivery')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retour de livraison',
                'verbose_name_plural': 'Retours de livraison',
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('moto', 'Moto'), ('tricycle', 'Tricycle'), ('car', 'Voiture'), ('pickup', 'Pickup'), ('van', 'Camionnette'), ('truck', 'Camion'), ('other', 'Autre')], help_text='Laisser vide pour tous les types de véhicule.', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('normal', 'Normale'), ('urgent', 'Urgente')], help_text='Laisser vide pour toutes les priorités.', max_length=20)),
                ('min_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant fixe ajouté si la règle correspond.', max_digits=10)),
                ('multiplier_percent', models.IntegerField(default=0, help_text='Majoration en % du total courant si la règle correspond (peut être négatif).')),
                ('label', models.CharField(help_text='Ex : Supplément camion hors zone', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer à toutes les zones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='deliveries.deliveryzone')),
            ],
            options={
                'verbose_name': 'Règle de tarification',
                'verbose_name_plural': 'Règles de tarification',
                'ordering': ['order', 'id'],
            },
        ),
    ]
