# Generated by Django 5.0.6 on 2026-09-17 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryexpense_deliveryreturn_pricingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryexpense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
