# Generated by Django 5.0.6 on 2026-09-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_delivery_last_latitude_delivery_last_location_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Compte utilisateur lié (facultatif) — donne accès à l'espace « Transporteur » (gestion de sa propre flotte et de ses livraisons).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
