# Generated by Django 5.0.6 on 2026-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_carrier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text='Photo de la CNI.', null=True, upload_to='deliveries/drivers/id_cards/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, help_text='Photo du permis de conduire.', null=True, upload_to='deliveries/drivers/licenses/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du chauffeur.', null=True, upload_to='deliveries/drivers/'),
        ),
    ]
