# Generated by Django 5.0.6 on 2026-09-19 14:00

import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_delivery_client_latitude_delivery_client_location_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text='Photo de la CNI.', null=True, upload_to='deliveries/drivers/id_cards/', validators=[apps.documents.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, help_text='Photo du permis de conduire.', null=True, upload_to='deliveries/drivers/licenses/', validators=[apps.documents.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du chauffeur.', null=True, upload_to='deliveries/drivers/', validators=[apps.documents.validators.validate_image_file]),
        ),
    ]
