# Generated by Django 5.0.6 on 2026-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
    ]
