# Generated by Django 5.0.6 on 2026-09-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='identity_number',
            field=models.CharField(blank=True, help_text="Numéro de pièce d'identité ou d'immatriculation du prestataire", max_length=50),
        ),
    ]
