# Generated by Django 5.0.6 on 2026-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_discount_label_provider_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
