# Generated by Django 5.0.6 on 2026-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_provider_address_provider_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('dj', 'DJ'), ('caterer', 'Traiteur'), ('decoration', 'Décoration'), ('security', 'Sécurité'), ('photography', 'Photographie'), ('video', 'Vidéo'), ('pastry', 'Pâtisserie'), ('animation', 'Animation (MC, artistes, danseurs...)'), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('printing', 'Impression'), ('other', 'Autre')], max_length=20),
        ),
    ]
