# Generated by Django 5.0.6 on 2026-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_provider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('dj', 'DJ'), ('caterer', 'Traiteur'), ('decoration', 'Décoration'), ('security', 'Sécurité'), ('photography', 'Photographie'), ('video', 'Vidéo'), ('pastry', 'Pâtisserie'), ('animation', 'Animation (MC, artistes, danseurs...)'), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('printing', 'Impression'), ('wedding_planner', 'Wedding planner'), ('florist', 'Fleuriste'), ('makeup_artist', 'Maquilleur(se)'), ('hairdresser', 'Coiffeur(se)'), ('sound', 'Sonorisation'), ('lighting', 'Éclairage'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre')], max_length=20),
        ),
    ]
