# Generated by Django 5.0.6 on 2026-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_provider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('wedding_planner', 'Wedding planner / Event planner'), ('mc', 'Maître de cérémonie (MC)'), ('protocol', 'Protocole'), ('venue_rental', 'Location de salle / domaine / villa / hôtel'), ('tent_rental', 'Location de chapiteaux, tentes, bâches'), ('furniture_rental', 'Location de chaises, tables, nappes, housses'), ('tableware_rental', 'Location de vaisselle, verrerie, couverts'), ('generator_electrician', 'Groupe électrogène + électricien'), ('security', 'Sécurité / Agents de sécurité / Videur'), ('cleaning_service', 'Service de nettoyage'), ('decoration', 'Décorateur / Designer événementiel'), ('florist', 'Fleuriste'), ('centerpiece_rental', 'Location de centre de table, arche, backdrop'), ('balloon_artist', 'Ballons / Artiste en ballons'), ('lighting', "Éclairage d'ambiance / Scénographie"), ('caterer', 'Traiteur / Service traiteur'), ('pastry', 'Pâtissier / Cake designer'), ('ice_cream_fountain', 'Glacier / Fontaine à chocolat'), ('bartender', 'Barman / Service bar / Bar à cocktail'), ('waitstaff', 'Serveurs / Serveuses'), ('photography', 'Photographe'), ('video', 'Vidéaste / Cameraman / Drone'), ('photobooth', 'Photobooth / Miroir photo / 360° Booth'), ('guestbook', "Livre d'or / Audioguest"), ('dj', 'DJ / Disc-jockey'), ('live_band', 'Groupe live / Orchestre / Artistes / Chanteurs'), ('sound', 'Sonorisation / Technicien son'), ('stage_lighting', 'Éclairagiste / Jeux de lumière / Fumigène'), ('animation', 'Animateurs / Danseurs / Danseuses'), ('entertainer', 'Humoriste / Magicien / Cracheur de feu'), ('mascot', 'Mascottes / Personnages pour enfants'), ('games_rental', 'Location de jeux (château gonflable, etc.)'), ('stylist', 'Styliste / Créateur de robes / Costumier'), ('makeup_artist', 'Maquilleuse (MUA)'), ('hairdresser', 'Coiffeuse'), ('manicure', 'Manucure / Onglerie'), ('costume_rental', 'Location de costumes / tenues traditionnelles'), ('luxury_car_rental', 'Location de voitures de luxe / Limousine'), ('guest_transport', 'Transport invités (bus, navette)'), ('hotel_booking', 'Réservation hôtel pour invités'), ('printing', 'Imprimerie (faire-part, invitations, menus)'), ('website_creator', "Créateur de site web pour l'événement"), ('jeweler', "Loueur d'alliances / Bijoutier"), ('childcare_service', "Service de gardiennage d'enfants (nounou)"), ('impresario', 'Impresario'), ('graphic_design', 'Graphisme & infographie'), ('equipment_rental', 'Location de matériel'), ('venue_manager', 'Responsable de salle'), ('agency', 'Agence événementielle'), ('interior_architect', "Architecte / designer d'intérieur"), ('other', 'Autre')], max_length=30),
        ),
    ]
