# Generated by Django 5.0.6 on 2026-09-19 09:54 — réordonnée à la main pour
# chiffrer le contenu existant avant de supprimer la colonne en clair.

from django.db import migrations, models


def encrypt_existing_bodies(apps, schema_editor):
    from apps.messaging.crypto import encrypt_text

    Message = apps.get_model("messaging", "Message")
    for message in Message.objects.exclude(body="").only("id", "body"):
        message.body_encrypted = encrypt_text(message.body)
        message.save(update_fields=["body_encrypted"])


def decrypt_existing_bodies(apps, schema_editor):
    from apps.messaging.crypto import decrypt_text

    Message = apps.get_model("messaging", "Message")
    for message in Message.objects.exclude(body_encrypted="").only("id", "body_encrypted"):
        message.body = decrypt_text(message.body_encrypted)
        message.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messaging/attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, help_text="Nom de fichier d'origine", max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, help_text="Taille d'origine en octets", null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Vidéo'), ('other', 'Autre')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='body_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing_bodies, decrypt_existing_bodies),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
