# Generated by Django 5.0.6 on 2026-09-06 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='discount_label',
            field=models.CharField(blank=True, help_text='Ex: Offre de rentrée', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='discount_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
