# Generated by Django 5.0.6 on 2026-09-06 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_discount_label_equipment_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée (réapprovisionnement)'), ('out', 'Sortie')], max_length=10)),
                ('reason', models.CharField(choices=[('restock', 'Réapprovisionnement / achat'), ('event_use', 'Utilisation pour un événement'), ('damage', 'Endommagé'), ('loss', 'Perdu / volé'), ('return', 'Retour en stock'), ('disposal', 'Mise au rebut'), ('other', 'Autre')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='equipment.equipment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('purchase', 'Achat de matériel'), ('maintenance', 'Maintenance / réparation'), ('logistics', 'Logistique / transport'), ('utilities', 'Charges (eau, électricité, internet)'), ('other', 'Autre')], default='other', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('incurred_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, help_text='Matériel concerné, le cas échéant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='equipment.equipment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='equipment.stockmovement')),
            ],
            options={
                'ordering': ['-incurred_at', '-created_at'],
            },
        ),
    ]
