# Generated by Django 5.0.6 on 2026-09-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_ref'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo prise à l'enrôlement, reprise sur le badge", null=True, upload_to='enrollments/'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_settlements', to='payments.payment'),
        ),
    ]
