# Generated by Django 5.0.6 on 2026-09-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_enrollment_photo_settlement_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.CharField(blank=True, choices=[('day', 'Cours du jour'), ('evening', 'Cours du soir')], max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Visible dans le catalogue des inscriptions'),
        ),
        migrations.AddField(
            model_name='training',
            name='perks',
            field=models.JSONField(blank=True, default=list, help_text='Avantages affichés sur le catalogue (wifi, matériel, suivi…)'),
        ),
        migrations.AddField(
            model_name='training',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainings/'),
        ),
        migrations.AddField(
            model_name='training',
            name='schedule_options',
            field=models.JSONField(blank=True, default=list, help_text='Ex: [{"label": "Cours du jour", "hours": "10H - 13H"}, {"label": "Cours du soir", "hours": "15H - 18H"}]'),
        ),
        migrations.AlterField(
            model_name='training',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Tarif de repli utilisé si aucune formule (durée) n'est définie pour cette filière", max_digits=12),
        ),
        migrations.AlterField(
            model_name='training',
            name='session_label',
            field=models.CharField(blank=True, help_text='Ex: Rentrée académique 2026', max_length=100),
        ),
        migrations.CreateModel(
            name='TrainingFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Formation accélérée', max_length=150)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text="Frais d'inscription", max_digits=12)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, help_text='Frais de formation', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='training.training')),
            ],
            options={
                'ordering': ['duration_months'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='formula',
            field=models.ForeignKey(blank=True, help_text="Formule (durée/tarif) choisie ; si absente, le tarif de repli de la filière s'applique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training.trainingformula'),
        ),
    ]
