# Generated by Django 5.0.6 on 2026-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('organizer', 'Organisateur'), ('participant', 'Participant / Élève'), ('employee', 'Employé')], default='participant', max_length=20),
        ),
    ]
