# Generated by Django 5.0.6 on 2026-09-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_until',
            field=models.DateTimeField(blank=True, help_text="Abonnement Premium Marketplace actif jusqu'à cette date.", null=True),
        ),
    ]
