# Generated by Django 5.0.6 on 2026-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_premium_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('organizer', 'Organisateur'), ('participant', 'Participant / Élève'), ('employee', 'Employé'), ('partner', 'Prestataire')], default='participant', max_length=20),
        ),
    ]
