# Generated by Django 5.0.6 on 2026-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text="Ville — renseignée à l'inscription.", max_length=100),
        ),
    ]
