# Generated by Django 5.0.6 on 2026-09-19 14:00

import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(upload_to='employees/job_applications/cv/', validators=[apps.documents.validators.validate_document_file]),
        ),
    ]
