# Generated by Django 5.0.6 on 2026-09-21 07:07

import apps.documents.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('activite', models.CharField(blank=True, help_text="Secteur d'activité", max_length=200)),
                ('rccm', models.CharField(blank=True, help_text='Numéro RCCM', max_length=100)),
                ('niu', models.CharField(blank=True, help_text="Numéro d'identifiant unique (NIU)", max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('representant', models.CharField(blank=True, help_text='Représentant légal', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('verification_status', models.CharField(choices=[('not_verified', 'Non vérifié'), ('profile_verified', 'Profil vérifié'), ('identity_verified', 'Identité vérifiée'), ('company_verified', 'Entreprise vérifiée'), ('portfolio_verified', 'Portfolio vérifié'), ('professional_partner', 'Partenaire professionnel')], default='not_verified', help_text="Statut de vérification, accordé par l'administration.", max_length=25)),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour masquer le profil sans le supprimer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='companies/documents/', validators=[apps.documents.validators.validate_document_file])),
                ('label', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.companyprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
