# Generated by Django 5.0.6 on 2026-09-21 07:07

import apps.documents.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('formation', models.TextField(blank=True, help_text='Formation / parcours académique')),
                ('competences', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=300)),
                ('experience', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('disponibilite', models.CharField(choices=[('immediate', 'Immédiate'), ('within_month', 'Sous 1 mois'), ('to_define', 'À définir')], default='to_define', max_length=20)),
                ('opportunity_type', models.CharField(choices=[('one_off', 'Mission ponctuelle'), ('fixed_term', 'CDD'), ('permanent', 'CDI'), ('internship', 'Stage'), ('freelance', 'Freelance')], default='one_off', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='talents/photos/', validators=[apps.documents.validators.validate_image_file])),
                ('verification_status', models.CharField(choices=[('not_verified', 'Non vérifié'), ('profile_verified', 'Profil vérifié'), ('identity_verified', 'Identité vérifiée'), ('company_verified', 'Entreprise vérifiée'), ('portfolio_verified', 'Portfolio vérifié'), ('professional_partner', 'Partenaire professionnel')], default='not_verified', help_text="Statut de vérification, accordé par l'administration.", max_length=25)),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour masquer le profil sans le supprimer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talents/portfolio/', validators=[apps.documents.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='talents.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
