# Generated by Django 5.0.6 on 2026-09-05 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre sterling')], default='XAF', max_length=3)),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('freemopay', 'FreemoPay'), ('kob', 'KOB'), ('demo', 'Mode démonstration')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_ref', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, help_text='Référence renvoyée par la passerelle', max_length=200)),
                ('purpose', models.CharField(default='ticket_purchase', help_text='ticket_purchase, training_fee, ...', max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['transaction_ref'], name='payments_pa_transac_80aa14_idx')],
            },
        ),
    ]
