# Generated by Django 5.0.6 on 2026-09-05 20:01

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(default=apps.payments.models.generate_transaction_ref, editable=False, max_length=64, unique=True),
        ),
    ]
