# Generated by Django 5.0.6 on 2026-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire (Visa / Mastercard)'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money'), ('freemopay', 'FreemoPay'), ('kob', 'KOB'), ('demo', 'Mode démonstration')], max_length=20),
        ),
    ]
