# Generated by Django 5.0.6 on 2026-09-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_buyer_email_ticket_buyer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Génère un billet PDF avec un visuel premium (billets VIP / prestige).'),
        ),
    ]
